services:
  - type: web
    name: car-sticker-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SERVER
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
